name: Build Spigot Plugin

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Catseedlogin
        path: src/*
